# Gitleaks configuration for secret scanning
# https://github.com/gitleaks/gitleaks

[extend]
useDefault = true

[allowlist]
description = "Allowlisted files and paths"
paths = [
    '''node_modules''',
    '''.git''',
    '''dist''',
    '''build''',
    '''.next''',
    '''out''',
]

# Additional custom rules for NeuraScale
[[rules]]
description = "Google Maps API Key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["key", "Google", "Maps"]

[[rules]]
description = "Vercel API Token"
regex = '''[vV][eE][rR][cC][eE][lL].*[0-9a-zA-Z]{24}'''
tags = ["key", "Vercel"]

[[rules]]
description = "Email Password"
regex = '''(EMAIL_PASS|EMAIL_PASSWORD|MAIL_PASSWORD)\s*=\s*['\"]?[^\s'\"]+['\"]?'''
tags = ["password", "email"]

# Exclude test files and examples
[allowlist.regexTarget]
regexTarget = "line"
regexes = [
    '''your-api-key-here''',
    '''your-email@gmail.com''',
    '''your-app-password''',
    '''example\.com''',
]