# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(node_modules|.next|dist|build)/
      - id: end-of-file-fixer
        exclude: ^(node_modules|.next|dist|build)/
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md)$
        exclude: ^(node_modules|.next|dist|build)/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^(node_modules|.next|dist|build)/
        args: ['--fix']
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-next@14.0.4
          - typescript@5.3.3

  # Python code quality tools for neural-engine
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^neural-engine/.*\.py$
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        files: ^neural-engine/.*\.py$
        args: ['--config=neural-engine/.flake8']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^neural-engine/.*\.py$
        args: ['--config-file=neural-engine/mypy.ini', '--namespace-packages']
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-protobuf
          - numpy
