# Jekyll configuration for NeuraScale Documentation
title: NeuraScale Documentation
description: Comprehensive documentation for NeuraScale - Open-source neuromorphic computing platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.neurascale.io" # the base hostname & protocol for your site

# Theme settings
theme: jekyll-theme-minimal
# Alternative themes that work well for documentation:
# theme: jekyll-theme-cayman
# theme: jekyll-theme-slate
# theme: jekyll-theme-dinky

# Build settings
markdown: kramdown
highlighter: rouge

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Collections for organizing documentation
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  console:
    output: true
    permalink: /:collection/:path/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
  - scope:
      path: ""
      type: "console"
    values:
      layout: "doc"
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Neural Management System
    url: /neural-management-system/
    sublinks:
      - title: Overview
        url: /neural-management-system/
      - title: Dataset Management
        url: /dataset-management/
      - title: Security & Encryption
        url: /security-encryption/
      - title: API Documentation
        url: /api-documentation/
  - title: Architecture
    url: /architecture/
    sublinks:
      - title: Technical Architecture
        url: /architecture/
      - title: Architecture Diagrams
        url: /architecture-diagrams/
  - title: Getting Started
    sublinks:
      - title: Overview
        url: /docs/
      - title: Environment Variables
        url: /docs/environment-variables/
      - title: Deployment Guide
        url: /docs/deployment/
  - title: Core Integrations
    sublinks:
      - title: Sanity CMS
        url: /docs/sanity-integration/
      - title: Neon Database
        url: /docs/neon-database/
  - title: Google Services
    sublinks:
      - title: Analytics Setup
        url: /docs/google-analytics-setup/
      - title: Ads Setup
        url: /docs/google-ads-setup/
      - title: Maps Troubleshooting
        url: /docs/fix-google-maps/
  - title: Console Application
    sublinks:
      - title: Console Overview
        url: /console/
      - title: Firebase Setup
        url: /console/firebase-setup/
      - title: Infrastructure
        url: /console/infrastructure/
  - title: Contributing
    url: /contributing/
  - title: Security
    url: /security/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
