export default {
  index: "",
  "get-started": "",
  architecture: "",
  "system-modeling": "",
  features: "",
  api: "",
  "developer-guide": "",
  "device-integration": "",
  configuration: "",
  deployment: "",
  security: "",
  "clinical-workflows": "",
  "ml-development": "",
  performance: "",
  monitoring: "",
  troubleshooting: "",
  contributing: "",
  integrations: "Third-Party Integrations",
  "release-notes": "Release Notes",
};
