{{- if .Values.deviceManager.enabled }}
apiVersion: {{ include "neural-engine.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "neural-engine.fullname" . }}-device-manager
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
    component: device-manager
spec:
  replicas: {{ .Values.deviceManager.replicas }}
  selector:
    matchLabels:
      {{- include "neural-engine.selectorLabels" . | nindent 6 }}
      component: device-manager
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "neural-engine.selectorLabels" . | nindent 8 }}
        component: device-manager
        version: {{ .Values.image.tag }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "neural-engine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deviceManager.podSecurityContext | default .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: device-manager
          securityContext:
            {{- if .Values.deviceManager.privileged }}
            privileged: true
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ .Values.deviceManager.image.repository }}:{{ .Values.deviceManager.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: grpc
              containerPort: 50052
              protocol: TCP
            - name: metrics
              containerPort: 9091
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: LOG_LEVEL
              value: {{ .Values.deviceManager.logLevel | default "info" }}
            {{- with .Values.deviceManager.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.deviceManager.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/device-manager
              readOnly: true
            {{- if .Values.deviceManager.usbAccess }}
            - name: usb
              mountPath: /dev/bus/usb
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "neural-engine.fullname" . }}-config
        {{- if .Values.deviceManager.usbAccess }}
        - name: usb
          hostPath:
            path: /dev/bus/usb
            type: Directory
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deviceManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
