{{- if .Values.mcpServer.enabled }}
apiVersion: {{ include "neural-engine.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "neural-engine.fullname" . }}-mcp-server
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
    component: mcp-server
spec:
  {{- if not .Values.mcpServer.autoscaling.enabled }}
  replicas: {{ .Values.mcpServer.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "neural-engine.selectorLabels" . | nindent 6 }}
      component: mcp-server
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9094"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "neural-engine.selectorLabels" . | nindent 8 }}
        component: mcp-server
        version: {{ .Values.image.tag }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "neural-engine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mcp-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mcpServer.image.repository }}:{{ .Values.mcpServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
            - name: metrics
              containerPort: 9094
              protocol: TCP
          env:
            - name: MCP_ENV
              value: {{ .Values.global.environment }}
            - name: LOG_LEVEL
              value: {{ .Values.mcpServer.logLevel | default "info" }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "neural-engine.fullname" . }}-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "neural-engine.fullname" . }}-secrets
                  key: redis-url
            {{- with .Values.mcpServer.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.mcpServer.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: cache
              mountPath: /app/cache
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "neural-engine.fullname" . }}-config
        - name: cache
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
