{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neural-engine.fullname" . }}-secrets
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: "postgresql://{{ .Values.postgresql.auth.username | default "postgres" }}:$(POSTGRES_PASSWORD)@{{ include "neural-engine.postgresqlHost" . }}:5432/{{ .Values.postgresql.auth.database }}"
  {{- else if .Values.externalPostgresql.enabled }}
  database-url: "postgresql://{{ .Values.externalPostgresql.username }}:$(POSTGRES_PASSWORD)@{{ .Values.externalPostgresql.host }}:{{ .Values.externalPostgresql.port }}/{{ .Values.externalPostgresql.database }}"
  {{- end }}

  {{- if .Values.redis.enabled }}
  redis-url: "redis://$(REDIS_PASSWORD)@{{ include "neural-engine.redisHost" . }}:6379"
  {{- else if .Values.externalRedis.enabled }}
  redis-url: "redis://$(REDIS_PASSWORD)@{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}"
  {{- end }}

  # Additional secrets can be added here
  jwt-secret: "{{ randAlphaNum 32 | b64enc }}"
  api-key-salt: "{{ randAlphaNum 16 | b64enc }}"
{{- end }}
