{{- if .Values.processor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neural-engine.fullname" . }}-processor
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
    component: processor
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "neural-engine.selectorLabels" . | nindent 4 }}
    component: processor
{{- end }}

{{- if .Values.deviceManager.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neural-engine.fullname" . }}-device-manager
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
    component: device-manager
  {{- with .Values.deviceManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.deviceManager.service.type }}
  ports:
    - port: {{ .Values.deviceManager.service.port }}
      targetPort: {{ .Values.deviceManager.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "neural-engine.selectorLabels" . | nindent 4 }}
    component: device-manager
  {{- if eq .Values.deviceManager.service.type "LoadBalancer" }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  {{- end }}
{{- end }}

{{- if .Values.apiGateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neural-engine.fullname" . }}-api-gateway
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
    component: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "neural-engine.selectorLabels" . | nindent 4 }}
    component: api-gateway
{{- end }}

{{- if .Values.mlPipeline.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neural-engine.fullname" . }}-ml-pipeline
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
    component: ml-pipeline
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    {{- include "neural-engine.selectorLabels" . | nindent 4 }}
    component: ml-pipeline
{{- end }}

{{- if .Values.mcpServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neural-engine.fullname" . }}-mcp-server
  labels:
    {{- include "neural-engine.labels" . | nindent 4 }}
    component: mcp-server
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
    - port: 9094
      targetPort: 9094
      protocol: TCP
      name: metrics
  selector:
    {{- include "neural-engine.selectorLabels" . | nindent 4 }}
    component: mcp-server
{{- end }}
