# Cloud Build configuration for Neural Engine
steps:
  # Build processor image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/neural-processor:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/neural-processor:latest'
      - '-f'
      - 'docker/Dockerfile.processor'
      - '.'

  # Build API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/neural-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/neural-api:latest'
      - '-f'
      - 'docker/Dockerfile.api'
      - '.'

  # Deploy API to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'neural-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/neural-api:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/neural-processor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/neural-processor:latest'
  - 'gcr.io/$PROJECT_ID/neural-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/neural-api:latest'

timeout: '1200s'
