# Grafana Datasource Configuration
# NeuraScale Kong Gateway Monitoring

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://kong-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData: {}
    uid: prometheus-kong
    version: 1
